# running on container-based infrastructure
sudo: false

language: node_js
node_js:
  - "node"
  
# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xenafable"
  - git config user.email "is_xuFenFen_smile@qq.com"
  - git add .
  - git commit -m "Testing Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: github.com/xenafable/xenafable.github.io.git
